FROM node:22-alpine AS frontend_builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM caddy:2-alpine
COPY --from=frontend_builder /app/dist /srv/frontend
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE 80 443
